# Generated by Django 3.2.5 on 2021-10-18 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishRod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('type', models.CharField(max_length=255, verbose_name='Тип удилища')),
                ('length', models.CharField(max_length=255, verbose_name='Длина удилища')),
                ('weight', models.CharField(max_length=255, verbose_name='Вес удилища')),
                ('transport_length', models.CharField(max_length=255, verbose_name='Транспортировочная длина')),
                ('number_of_sections', models.CharField(max_length=255, verbose_name='Количество секций')),
                ('maximum_test', models.CharField(max_length=255, verbose_name='Максимальный тест')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категоря')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FishLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('type', models.CharField(max_length=255, verbose_name='Тип лески')),
                ('diameter', models.CharField(max_length=255, verbose_name='Диаметр лески')),
                ('breaking_load', models.CharField(max_length=255, verbose_name='Разрывная нагрузка')),
                ('length', models.CharField(max_length=255, verbose_name='Длина лески')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет лески')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категоря')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
